### ISSUE TITLE
ALiVE friendly facties maken op basis van Cammo

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/NLD_Units#24]
Dit is inmiddels nodig geworden ivm 3DEN. Alle units zijn onder dezelfde factie/noemer in de editor en de enige manier om iemand uit te zoeken op basis van camo is in de hint/pop-up ding in de editor.

In het kort:
- [ ] NLD Units moet dezelfde structuur krijgen wat er voor OPFOR gebruikt gaat worden
- [ ] Vests en Helmen moeten ff nagelopen worden. Want de helmen bijv hebben geen armour values (dus we zitten voor nu gewoon vast aan vanilla stuff)
- [ ] Spullen opsplitsen op basis van camo
- [ ] De config opsplitsen en includen (zoals nu met de template gedaan wordt) met daarin aparte includes voor units, helmen, backpacks, groepen etc. Zo kunnen mensen met 1 dingen werken zonder massive merge conflicts.
- [ ] Voertuigen op basis van camo in een factie meenemen
- [ ] Air vehicles opnemen in 1 factie omdat ze tamelijk unverseel zijn.
- [ ] Groepen config moet ook een beetje aangedikt worden/herschreven.

**Comment by Ligthert** [comment]
En dit wil ik weer gaan oppakken en dan per factie een eigen mapje geven (zoals in **_OPFOR**).

**Comment by Ligthert** [comment]
Dit is inmiddels nodig geworden ivm 3DEN. Alle units zijn onder dezelfde factie/noemer in de editor en de enige manier om iemand uit te zoeken op basis van camo is in de hint/pop-up ding in de editor.

In het kort:
- [ ] NLD Units moet dezelfde structuur krijgen wat er voor OPFOR gebruikt gaat worden
- [ ] Vests en Helmen moeten ff nagelopen worden. Want de helmen bijv hebben geen armour values (dus we zitten voor nu gewoon vast aan vanilla stuff)
- [ ] Spullen opsplitsen op basis van camo
- [ ] Voertuigen op basis van camo in een factie meenemen
- [ ] Air vehicles opnemen in 1 mod
- [ ] Groepen config moet ook een beetje aangedikt worden/herschreven.

**Comment by ancorb1974** [comment]
Helmen geen wat.
	
	class NLD_DST_Helmet : H_HelmetIA {
		dlc="NLD_Units";
		author="Lowlands Tactical";
		scope = 2;
		weaponPoolAvailable = 1;
		displayName = "[NLD] Desert Helmet";
		picture = "\NLD_Infantry_Units\Units\Desert\Data\uim\Helmet.paa";
		model = "\A3\Characters_F_Beta\INDEP\headgear_helmet_canvas";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\NLD_Infantry_Units\Units\Desert\Data\Helmet.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 1;
			uniformModel = "\A3\Characters_F_Beta\INDEP\headgear_helmet_canvas";
			modelSides[] = {3, 1};
			armor = 6;
			passThrough = 0.5;
			hiddenSelectionsTextures[] = {"\NLD_Infantry_Units\Units\Desert\Data\Helmet.paa"};
			hiddenSelections[] = {"camo"};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=6;
					passThrough=0.5;
				};
			};
		};
	};
Vesten geen wat ??

	class NLD_WLD_Vest : V_PlateCarrierIA2_dgtl {
		dlc="NLD_Units";
		author="Lowlands Tactical";
		scope = 2;
		displayName = "[NLD] Woodland Vest";
		picture = "\NLD_Infantry_Units\Units\Desert\Data\uim\Vest.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\NLD_Infantry_Units\Units\Desert\Data\Vest.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
			containerClass = "Supply120";
			mass = 1;
			hiddenSelections[] = {"camo"};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					hitpointName="HitChest";
					armor=16;
					passThrough=0.30000001;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=16;
					passThrough=0.30000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=16;
					passThrough=0.30000001;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=16;
					passThrough=0.30000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.30000001;
				};
			};
		};
	};

**Comment by Ligthert** [comment]
Dit is gedaan. Kan dicht.
