### ISSUE TITLE
Add 1980's camouflage to units

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/NLD_Units#5]

**Comment by ancorb1974** [comment]
heb ik bijna klaar, moet nog eventjes met de helm iets fixxen

**Comment by Ligthert** [comment]
@ancorb1974 Heb jij wat config voor me of een mapje met textures?

**Comment by ancorb1974** [comment]
Ja maar ook hier zit ik met de sp_pack en zijn uv & de helmen.
Wat we bij OPFOR ook hadden dat als je binnen staat de zon nog op de helm blijft.
Bij OPFOR heb ik het een ander model helm gegeven, bij 80's kan dit niet.
Of we nemen het voor lief of een andere helm.. maar welke :)

**Comment by ancorb1974** [comment]
Alleen de backpacks moeten nog gevuld worden.

**Comment by ancorb1974** [comment]
80's Units fully integrated
